version: '3.1'
services:
  stats-server:
    build: stats/stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - spring.datasource.url=jdbc:postgresql://stats-db:5432/explore-with-me-stats
      - spring.datasource.username=person
      - spring.datasource.password=123
      - stat-client.name=ewm-main-service
      - stats-server.uri=http://stats-server:9090

  stats-db:
    image: postgres:14-alpine
    container_name: statistic_database
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me-stats
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=123

  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/explore-with-me-ewm
      - spring.datasource.username=admin
      - spring.datasource.password=admin
      - stat-client.name=ewm-main-service
      - stats-server.uri=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_database
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore-with-me-ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
