version: '3.1'
services:
  stats:
    build: ./stats/stats-service
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - stats-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    volumes:
      - ewm-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  stats-db:
  ewm-db: